# Using Logistic Regression on Features extracted using CNN

In [1]:
import numpy as np

In [21]:
file_path = "../../heli_and_boat.tar/"
file_boat = "boat_features_cnn.csv"
file_heli = "heli_features_cnn.csv"
boat_X = np.genfromtxt(file_path+file_boat,delimiter=",",dtype=None)
heli_X = np.genfromtxt(file_path+file_heli,delimiter=",",dtype=None)

In [45]:
X = np.concatenate((boat_X,heli_X))
Y = np.zeros((len(boat_X)+len(heli_X)))
Y[len(boat_X):] = 1
Y = Y.astype('int')

In [46]:
from sklearn.linear_model import LogisticRegression

In [56]:
data = np.concatenate((X,Y[np.newaxis].T),axis=1)

In [57]:
np.random.shuffle(data)

In [64]:
data.sum(axis=0)

array([ 624.09374111,  158.75781955,  508.79236773, ...,  818.41696824,
        313.20773755,  442.        ])

In [63]:
np.concatenate((X,Y[np.newaxis].T),axis=1).sum(axis=0)

array([ 624.09374111,  158.75781955,  508.79236773, ...,  818.41696824,
        313.20773755,  442.        ])

In [73]:
X,Y = data[:,:-1],data[:,-1]

In [74]:
X.shape,Y.shape

((852L, 1024L), (852L,))

In [79]:
X_train, Y_train = X[:700],Y[:700]
X_test, Y_test = X[700:],Y[700:]

In [97]:
clf = LogisticRegression(penalty='l2')

In [98]:
clf.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [99]:
clf.score(X_test,Y_test)

0.98684210526315785

In [117]:
from sklearn.model_selection import cross_val_score

In [119]:
# scores = cross_val_score(clf, iris.data, iris.target, cv=5)
scores = cross_val_score(clf, X_train, Y_train, cv=5)

In [121]:
scores

array([ 0.95035461,  0.94285714,  0.92142857,  0.97142857,  0.97122302])